name: benchmark-dotnet-sql2025

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  Path_Tests: './src/BenchmarkingDapperEFCoreCRMSqlServer'
  Path_ArtifactsBenchmarking: '/src/BenchmarkingDapperEFCoreCRMSqlServer/BenchmarkDotNet.Artifacts/results'
  ArtifactBenchmarkingHtml: 'BenchmarkingDapperEFCoreCRMSqlServer.Tests.CRMTests-report.html'
  ArtifactBenchmarkingMarkdown: 'BenchmarkingDapperEFCoreCRMSqlServer.Tests.CRMTests-report-github.md'
  NoContatosPorCompanhia: '2'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Exibir versoes instaladas do .NET SDK
        run: |
          echo '*** SDKs do .NET instalados ***'
          dotnet --list-sdks
          echo '*** Versão assumida como default para o .NET ***'
          dotnet --version

      - name: Setup .NET 10 Release Candidate 1
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.100-rc.1.25451.107'

      - name: Exibir versoes instaladas do .NET SDK (parte 2)
        run: |
          echo '*** SDKs do .NET instalados ***'
          dotnet --list-sdks
          echo '*** Versão assumida como default para o .NET ***'
          dotnet --version